name: DropParty
version: ${project.version}
main: me.aphotic.dropparty.DropParty
authors: [aphotic]
description: Customizable vault drop party
commands:
  dropparty:
    description: executes a drop party
